apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: default
  labels:
    k8s-app: httpd
spec:
  containers:
  - name: httpd
    image: nginx
    
---
kind: Service
apiVersion: v1
metadata:
  name: httpd
  namespace: default
spec:
  selector:
    k8s-app: httpd
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: ClusterIP